### ISSUE TITLE
Please make it a runable program like alphagen

### ISSUE THREAD

**Issue by Ray-0403** [x35f/alpha2#2]
Hi, it's really a wonderful work, please update it and make it a runable program and enable us to add custom operations..... and test it

**Comment by x35f** [comment]
Hi, thanks for liking our work. However, we apologize that we do not plan to release a fully runnable version of our work. The paper, together with the code structure and annotations should be sufficient for a re-implementation. If you have any questions w.r.t the problems encountered during re-implementation, we are happy to help.
