### ISSUE TITLE
maybe Incorrect Indexing for Start and Finish Tokens

### ISSUE THREAD

**Issue by zhangbonian** [x35f/alpha2#3]
Description
In the tokens.py file, the indexing for start_token_idx and finish_token_idx appears to be incorrect. The current implementation may lead to incorrect token identification and potential bugs in token processing.
Current Implementation
operator_tokens = UNARY_OP_TOKENS + BINARY_OP_TOKENS + TERNARY_OP_TOKENS + START_FINISH_TOKENS 
start_token_idx = len(operator_tokens) - 3
finish_token_idx = len(operator_tokens) - 2
Proposed Correction
operator_tokens = UNARY_OP_TOKENS + BINARY_OP_TOKENS + TERNARY_OP_TOKENS + START_FINISH_TOKENS 
start_token_idx = len(operator_tokens) - 2
finish_token_idx = len(operator_tokens) - 1
Rationale
Assuming START_FINISH_TOKENS contains two tokens (start and finish) and they are appended at the end of the operator_tokens list:

The start token should be the second-to-last element (index -2)
The finish token should be the last element (index -1)

The current implementation incorrectly assigns these indices, potentially causing misidentification of start and finish tokens.

**Comment by x35f** [comment]
Thanks for reporting this bug. We have fixed this in the latest commit.
