### ISSUE TITLE
how to evaluate partial expression

### ISSUE THREAD

**Issue by zhangbonian** [x35f/alpha2#4]
Hi,
for a partial program like this:
(Start, Null, Null, Null)
(Sub, close, open, Null)
(Sub, high, low, Null)
what's the proper way to assign its reward ?

**Comment by x35f** [comment]
As described in 4.1.2 in the paper, evaluating an alpha program involves reading values from the Reg0 register either during program construction or after its completion. This applies to both a partial program and a complete program.

**Comment by zhangbonian** [comment]
Thanks for clarifying that.
