### ISSUE TITLE
self.apha.apply_action is not defined

### ISSUE THREAD

**Issue by Moofeng** [x35f/alpha2#6]
参考源码，这里的action类型是int，我理解它代指一条instruction tuple
https://github.com/x35f/alpha2/blob/cfc4d44ea4a6e530e8bcd40e6f59af9888e8bb38/alpha2/mcts/game.py#L82-L83
https://github.com/x35f/alpha2/blob/cfc4d44ea4a6e530e8bcd40e6f59af9888e8bb38/alpha2/mcts/game.py#L21-L22

而在ExpressionTree类中并没有找到apply_action。我看到有add_action的方法，但是它的参数action貌似是tuple类型
https://github.com/x35f/alpha2/blob/cfc4d44ea4a6e530e8bcd40e6f59af9888e8bb38/alpha2/expression/tree.py#L23-L26

结合论文内容：
> In our alpha program environment, the state space, 𝒮, contains all potential alpha programs. Each state s corresponds to a unique alpha function ζ. A state s is a vectorized representation of the alpha function ζ. 

如果我没理解错的话，每个AlphaEnv中的self.program列表对应一条alpha program，其中包含的应该是不同长度的instruction tuple

此外，论文中提到：
> As outlined in (Tulchinsky, [2019](https://arxiv.org/html/2406.16505v2#bib.bib12)), diversity among alphas helps buliding robust trading strategies. In our framework, we incorporate such a target within the evaluation function. The diversity can be quantified by computing the correlation between alphas.

为了实现多样化，在evaluation function中需要计算与其他alpha program的相关系数，但是AlphaEnv中并未维护其它的alpha program，在它内部的evaluate方法应该无法实现这一点

综上，我有两点疑问：
1. self.apha.apply_action是否未定义？如果是，它要做哪些事情？
2. evaluation metric中的相关性计算在哪一步进行？

**Comment by x35f** [comment]
你好。
第一个问题：实际实现的时候，apply_action的action对应mcts节点中存储的action_index（int类型）用于节省内存，在tree中add_action需要计算实际因子值，所以中间会有一步转换。self.program中存储的的是转换过的action。
第二个问题：可以通过全局变量定义alpha pool，然后根据文章中的公式计算折扣IC。
